/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grapheditor.gui;

import grapheditor.algos.IntersectionGraphComputer;
import graphs.graph.Edge;
import graphs.graph.Graph;
import java.awt.BorderLayout;

/**
 *
 * @author sander
 */
public class IntersectionDAGDialog extends javax.swing.JDialog {

    private Graph intersectionGraph;
    private final MyDrawPanel drawPanel;

    /**
     * Creates new form IntersectionDAGDialog
     */
    public IntersectionDAGDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        drawPanel = new MyDrawPanel();
        getContentPane().add(drawPanel, BorderLayout.CENTER);
    }

    public void computeIntersectionGraph(Graph g) {
        intersectionGraph = IntersectionGraphComputer.computeIntersectionGraph(g.getVertices());
        drawPanel.setGraph(intersectionGraph);

        System.out.println("Number of edges2: " + intersectionGraph.getEdges().size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private class MyDrawPanel extends BasicGraphDrawPanel {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
